---
# tasks file for awx
- name: check system requirements
  assert:
    that:
      - ansible_memtotal_mb >= 2048
      - ansible_processor_vcpus >= 2
    msg: >
      Your system does not minimum system requirements, based on
      https://github.com/ansible/awx/blob/devel/INSTALL.md#system-requirements
      Your system has {{ ansible_memtotal_mb }} mb memory and {{ ansible_processor_vcpus }} cpus.

- name: get tags
  uri:
    url: https://api.github.com/repos/ansible/awx/tags
  register: awx_get_tags

- name: pick most recent tag
  set_fact:
    awx_version: "{{ item.name }}"
  with_items:
    - "{{ awx_get_tags.json | first }}"

- name: unarchive software
  unarchive:
    src: "https://github.com/ansible/awx/archive/{{ awx_version }}.tar.gz"
    dest: /tmp
    remote_src: yes
    creates: "/tmp/awx-{{ awx_version }}"
  notify:
    - run awx installer

- name: configure inventory
  template:
    src: inventory.j2
    dest: "/tmp/awx-{{ awx_version }}/installer/inventory"

- name: install requirements
  pip:
    name: "{{ awx_pip_requirements }}"
    state: "{{ awx_package_state }}"
  register: awx_install_requirements
  until: awx_install_requirements is succeeded
  retries: 3

- name: install requirements on localhost
  pip:
    name: ansible-tower-cli
    state: "{{ awx_package_state }}"
  connection: local
  register: awx_install_requirements_on_localhost
  until: awx_install_requirements_on_localhost is succeeded
  retries: 3

- name: flush handlers
  meta: flush_handlers

- name: configure organizations
  include: organization.yml
  with_items: "{{ awx_organizations }}"
  loop_control:
    loop_var: organization
  when:
    - awx_organizations is defined
